# FROM golang:1.13.4-alpine3.10
# FROM registry.ci.openshift.org/stolostron/builder:go1.17-linux AS builder

FROM locustio/locust AS builder

WORKDIR /go/src/github.com/stolostron/search-v2-api
CMD pwd && ls
COPY . .

CMD pwd && ls

ARG HOST="localhost"
ARG N_USERS=3
ARG RUN_TIME="20m" 

ENV N_USERS=$N_USERS
ENV API_TOKEN=$API_TOKEN
ENV HOST=$HOST

RUN echo "APITOKEN=$API_TOKEN"
RUN echo "RUN_TIME=$RUN_TIME"
ENTRYPOINT "./locust.sh"
