package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.31

import (
	"context"

	"github.com/stolostron/search-v2-api/graph/generated"
	"github.com/stolostron/search-v2-api/graph/model"
	"github.com/stolostron/search-v2-api/pkg/resolver"
	klog "k8s.io/klog/v2"
)

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, input []*model.SearchInput) ([]*resolver.SearchResult, error) {
	klog.V(2).Infof("-- Received search query with [%d] inputs --", len(input))
	for i, input := range input {
		if klog.V(3).Enabled() { // Avoids evaluating the input string.
			klog.Infof("-- input[%d]: %s", i, input.String())
		}
	}
	return resolver.Search(ctx, input)
}

// SearchComplete is the resolver for the searchComplete field.
func (r *queryResolver) SearchComplete(ctx context.Context, property string, query *model.SearchInput, limit *int) ([]*string, error) {
	klog.V(2).Infof("Received SearchComplete query with input property [%s] and limit [%+v]", property, *limit)

	return resolver.SearchComplete(ctx, property, query, limit)
}

// SearchSchema is the resolver for the searchSchema field.
func (r *queryResolver) SearchSchema(ctx context.Context) (map[string]interface{}, error) {
	klog.V(3).Infoln("Received SearchSchema query")
	return resolver.SearchSchemaResolver(ctx)
}

// Messages is the resolver for the messages field.
func (r *queryResolver) Messages(ctx context.Context) ([]*model.Message, error) {
	klog.V(3).Infoln("Received Messages query")
	return resolver.Messages(ctx)
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
